@echo off
cd /d "d:\Downloads\Customer Engagement Platform (1)"
echo Removing inner .git...
rmdir /s /q "Customer Engagement Platform\.git" 2>nul
echo Clearing git cache for folder...
git rm -r --cached "Customer Engagement Platform" 2>nul
echo Re-adding folder contents...
git add "Customer Engagement Platform"
echo Committing changes...
git commit -m "docs: fix nested git issue and upload all files"
echo Done.
